# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'blindOsu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftySound'
  
  # Pods for blindOsu

  target 'blindOsuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'blindOsuUITests' do
    # Pods for testing
  end

end
